---
title: "Blurb Books"
author: "Patrick Kelly"
date: "2/18/2020"
output: html_document
---

# Africa

In August 1972, after a year of planning and equipping, Val and Pat and cousin Wes left Kinshasa, Zaire headed east in our Landrover. Ten months, many countries and thousands of miles later, after many haps and mishaps, we sold the Landrover in Asmara, flew to Khartoum, and ended our African adventure by taking the train, riding 4th class, to Egypt, and finally flying to Europe and the US.


[Click Here](https://www.blurb.com/books/917643-distances)"Distances"

### Mali

[Click Here](https://www.blurb.com/books/1244097-sidib-ani-alou-ka-furusiri)"Sibé's and Aliou's Wedding"

# Maine

[Click Here](https://www.blurb.com/books/1378738-have-kayak-will-paddle)"Have Kayak, Will Paddle"

### Marathon

MDI marathon -- October 20, 2013

[Click Here](https://www.blurb.com/books/4745942-racing-glad)"MDI - Marathon"

### Peaks Island

Valerie and I became Maineiacs in December 1995, moving to a house we had bought over a year earlier on the backshore of Peaks Island, just a 20 minute ferry ride from Portland. Our first priority was to install an outdoors hot tub on our back deck.

Six months later our second priority was, you guessed it, to get a dog, for we soon realized that we had landed smack dab in the middle of a dog loving culture. One morning I asked a woman, walking with two beautiful Siberian huskies, where I could find out more about this breed. Silly question...the internet, of course.

[Click Here](https://www.blurb.com/books/1285549-cisco-unleashed)"Purebred...Pure Delight"

Dog lover, community organizer, political activist, and neighbor extraordinaire, Marjorie, who can be seen daily walking her collies and cat, along or near the backshore, recently celebrated her 70th birthday.


[Click Here](https://www.blurb.com/books/930134-marjorie-s-world)"Marjorie's World"


[Click Here](https://www.blurb.com/books/1072374-peaks-island-council-round-3)"Peaks Island Council:Round 3"

[Click Here](https://www.blurb.com/books/971492-playful-pixels)"Playful Pixels"

Youssouf's Peaks Island Escapade's Peaks Island Escapade

[Click Here](https://www.blurb.com/books/1120925-twas-midnight-on-the-ocean)"Youssouf Maggasouba"

### North Woods
Although Adama Koné, known to his friends as Damus or Mogotoro, searched long and hard, he saw nary a moose nor heard the cry of a loon, distant or otherwise. Neither did he have opportunity to dip a kayak/canoe paddle into the chilly waters of Lake Moosehead.

Adama did, however, get to sample the flapjacks at Kokadjo, learned how to navigate the Appalachian Trail via blazes and GPS coordinates, and enjoyed the 'Eye Candy' of Maine at the height of the Leaf Peeping season.

[Click Here](https://www.blurb.com/books/2601169-adama-s-maine-romps-october-2011)"Adama Koné's Romps"

Fifty-four miles on the Allagash Wilderness Waterway: July 12-17, 2009

[Click Here](https://www.blurb.com/books/798562-allagash-bash)"Alagash Bash"

In August 2015, the Northern Forest Canoe Trail, aided by volunteers and the Maine Conservation Corps, organized work to improve a short portage at the Demo Bridge on the Moose River, between Long Lake and Little Brassua Lake.

[Click Here](https://www.blurb.com/books/6413134-between-a-rock-and-a-hard-stump)"Between a Rock and a Hard Stump"

[Click Here](https://www.blurb.com/books/9766432-monumental)"Monumental"

[Click Here](https://www.blurb.com/books/3034422-reeady-hike)"Ready Hike!"

[Click Here](https://www.blurb.com/books/4188902-reeady-hike)"Ready Hike! The Duology"


# Ireland

The two-week expedition began on July 14, when our gang of 9 congregated in Ireland with a playbook:
Galway, Aran Islands (Inishmaan), Connemara National Park (Diamond Hill), Westport (Croagh Patrick), Dingle Peninsula (3-day hill walk), and ended in Dublin.

[Click Here](https://www.blurb.com/books/7279775-eireland-unclamped)"Eireland-unclamped"

# Massachusets

This book celebrates Andy's new hip by telling the story of a gathering of friends and family who rambled with him along the Cape Cod Canal on June 18, 2016.

[Click Here](https://www.blurb.com/books/7202559-canal-of-dreams)"Canal 0f Dreams"

# Nova-Scotia

[Click Here](https://www.blurb.com/books/9039910-look-offs)"Look-Offs"


# Virginia

Our gang in Virginia

[Click Here](https://www.blurb.com/books/850791-virginia-creepers)"Virginia Creeprs"

GW Parkway Classic 10 Miler - 2010

[Click Here](https://www.blurb.com/books/1319170-gatherings)"GW Parkway Classic"

# Offline Worldwide Learning

Where There is No Internet

[Click Here](https://www.blurb.com/books/6029330-offline-worlwide-learning)"RACHEL"

# Andy

[Click Here](https://www.blurb.com/books/3549214-andy-sketched)" Off thte Beaten Path"

